name: Clickable Pipeline

# Allows manual trigger from GitHub UI
on:
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Execute Permission for Scripts
        run: chmod +x ./pipeline.sh ./deploy.sh

      - name: Run Pipeline Script
        run: ./pipeline.sh

      - name: Run Deploy Script
        run: ./deploy.sh
