name: Pipeline Check
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Make scripts executable
        run: |
          chmod +x scripts/pipeline.sh
          chmod +x scripts/deploy.sh
      
      - name: Run pipeline
        run: cd scripts && ./pipeline.sh